
#- name: Build
#  steps: 
#   - runScriptConfig:
#      image: mcr.microsoft.com/dotnet/sdk:6.0
#      shellScript: dotnet restore
stages:
- name: Publish
  steps: 
  - publishImageConfig:
    dockerfilePath: ./Dockerfile
    buildContext: .
    tag: consulta-pedido:${CICD_EXECUTION_SEQUENCE}

#- name: Deploy
#  steps:
#   - applyYamlConfig:
#       path: ./deployment.yml
