stages:
- name: Gerar Imagem do Consulta Pedido
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: COP:${CICD_EXECUTION_SEQUENCE}        
- name: Deploy
  steps:
  - applyYamlConfig:
      path: deployment.yml
