stages:
- name: Codeception test
  steps:
  - runScriptConfig:
      image: mcr.microsoft.com/dotnet/sdk:6.0
      shellScript: |-
        dotnet restore
        dotnet publish -c Debug -o out
- name: Publish image
  steps:
  - publishImageConfig:
      shellscript: |-
      docker login -u jsmarzaro -p kerberos2@@6
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: jsmarzaro/consultapedido:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: docker-hub
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
- name: Deploy
  steps:
  - applyYamlConfig:
      path: deployment.yml
