stages:
- name: Codeception test
  steps:
  - runScriptConfig:
      image: mcr.microsoft.com/dotnet/sdk:6.0
      shellScript: |-
        dotnet restore
        dotnet publish -c Debug -o out        
- name: Publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
       tag: consulta-pedido-operacao:${CICD_EXECUTION_SEQUENCE}
      #tag: consultapedido:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: ghcr
      
- name: Deploy
  steps:
  - applyYamlConfig:
      path: deployment.yml
