
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consultapedido-server
  labels:
    app: cop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cop
  template:
    metadata:
      labels:
        app: cop
    spec:
      imagePullSecrets:
      -name: pipeline-docker-registry
      containers:
      - name: cop
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 80
      
      
---
kind: Service
apiVersion: v1
metadata:
  name: dotnet-service
spec:
  selector:
    app: cop
  type: clusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  #namespace: go
  name: p-lzzh7-pipeline-ingress
  annotations:
    allow.http: "true"
spec:
  rules:
  - host: cop.rancher.selia.com.br
    http:
      paths:
        - path: /
          backend:
            serviceName: dotnet-service
            servicePort: 80
