
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cop
spec:
  selector:
    matchLabels:
      run: cop
  replicas: 1
  template:
    metadata:
      labels:
        run: cop
    spec:
      containers:
      - name: cop
        image: ghcr.io/seliafullcommerce/consulta-pedido-operacao:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cop
  labels:
    run: cop
spec:
  ports:
  - port: 80
  selector:
    run: cop


---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  #namespace: go
  name: cop-ingress
  annotations:
    allow.http: "false"
spec:
  rules:
  - host: cop.rancher.selia.com.br
    http:
      paths:
        - path: /
          backend:
            serviceName: cop
            servicePort: 80