
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consultapedido-server
  labels:
    app: cop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cop
  template:
    metadata:
      labels:
        app: cop
    spec:
      imagePullSecrets:
       - name: dockerhub
      containers:
      - name: cop
         image: hub.docker/jsmarzaro/consultapedido:latest
        #image: ghcr.io/seliafullcommerce/consulta-pedido-operacao:latest
        #image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: cop-service
  #namespace: go
spec:
  selector:
    app: cop
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  #namespace: go
  name: cop-ingress
  annotations:
    allow.http: "true"
spec:
  rules:
  - host: cop.rancher.selia.com.br
    http:
      paths:
        - path: /
          backend:
            serviceName: cop-service
            servicePort: 80
